# Generated by Django 5.0 on 2024-01-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_delete_bankruptmodel_transaction_is_bankrupt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_bankrupt',
        ),
    ]
